pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo 'Build Stage'
            }
        }
        stage('clean stage'){
            steps{
                sh 'cd jenkins_file && mvn clean'
            }
        }
        stage('package'){
            steps{
                sh 'cd jenkins_file && mvn package'
            }
        }
        stage('package upload'){
            steps{
                sh 'git add .'
                sh 'git commit -m "Commit from jenkins"'
                sh 'git push origin jenkins_file'
            }
        }
    }
}