pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo 'Build Stage'
            }
        }
        stage('clean stage'){
            steps{
                sh 'cd jenkins_file && mvn clean'
            }
        }
    }
}